########################################
## RESOURCES ##
########################################

# fastq download
get_fastq_pe:
    threads: 2
    mem: 16000
# compress fastq
gzip_fastq:
    mem: 16000
# fastp program
fastp:
    threads: 2
    mem: 16000
# index reference
index_ref:
    mem: 16000
# genmap map
genmap:
    threads: 2
    mem: 32000
genmap_sort:
    mem: 32000
  # bwa mapping
bwa_map:
    threads: 4
    mem: 32000
# sort bam with picard's SortSam tool
sort_bam:
    mem: 16000
# mark duplicates with picard's MarkDuplicates
dedup:
    threads: 4
    mem: 32000
# calculate BAM summaries with samtools and picard
bam_sumstats:
    mem: 16000
merge_bams:
    mem: 32000
bedtools:
    mem: 32000
    
###
# Intervals workflow
###

# preprocess genome, create intervals
# picard's create CreateSequenceDictionary, samtools faidx
process_ref:
    mem: 16000
# custom python algo to create intervals
create_db_intervals:
  mem: 32000

create_gvcf_intervals:
  mem: 32000

## Callable sites workflow

# genmap map
genmap:
    threads: 4
    mem: 32000
genmap_sort:
    mem: 32000
compute_d4:
    mem: 16000
    threads: 4
merge_d4:
    mem: 16000
callable_bed:
    mem: 64000

###
# bam2vcf workflows
###

# gatk HaplotypeCaller
bam2gvcf:
    mem: 32000
# gatk GenomicsDBImport
gvcf2DB:
    mem: 32000
# gatk GenotypeGVCFs
DB2vcf:
    mem: 32000
## freebayes program only! ##
bam2vcf:
    mem: 32000
# gatk filterVcfs
filterVcfs:
    mem: 32000
# gatk GatherVcfs
gatherVcfs:
    mem: 64000
# picard SortVcf
sortVcf:
    mem: 32000
# vcftools program
vcftools:
    mem: 16000
# bedtools program
bedtools:
    mem: 32000
# plink
plink:
    threads: 2
admixture:
    mem: 16000
