__default__:
    time: 1-00:00:00
    nodes: 1
    mem: 32G
    cpus-per-task: 2
    output: "logs/slurm/slurm-%j.out"
    error: "logs/slurm/slurm-%j.err"

# fastq2bam workflow

get_fastq_pe:
    time: 1-00:00:00
    nodes: 1
    mem: 16G
    cpus-per-task: 2

gzip_fastq:
    time: 1-00:00:00
    nodes: 1
    mem: 16G
    cpus-per-task: 2

fastp:
    time: 1-00:00:00
    nodes: 1
    mem: 16G
    cpus-per-task: 2

index_ref:
    time: 1-00:00:00
    nodes: 1
    mem: 16G
    cpus-per-task: 2

genmap:
    time: 1-00:00:00
    nodes: 1
    mem: 32G
    cpus-per-task: 4

genmap_sort:
    time: 1-00:00:00
    nodes: 1
    mem: 32G
    cpus-per-task: 2

bwa_map:
    time: 1-00:00:00
    nodes: 1
    mem: 32G
    cpus-per-task: 4

sort_bam:
    time: 1-00:00:00
    nodes: 1
    mem: 25G
    cpus-per-task: 2

dedup:
    time: 1-00:00:00
    nodes: 1
    mem: 32G
    cpus-per-task: 4

bam_sumstats:
    time: 1-00:00:00
    nodes: 1
    mem: 16G
    cpus-per-task: 2

merge_bams:
    time: 1-00:00:00
    nodes: 1
    mem: 32G
    cpus-per-task: 2

bedtools:
    time: 1-00:00:00
    nodes: 1
    mem: 32G
    cpus-per-task: 2

# Intervals workflow

process_ref:
    time: 1-00:00:00
    nodes: 1
    mem: 16G
    cpus-per-task: 2

create_db_intervals:
    time: 1-00:00:00
    nodes: 1
    mem: 32G
    cpus-per-task: 2

create_gvcf_intervals:
    time: 1-00:00:00
    nodes: 1
    mem: 32G
    cpus-per-task: 2

# Callable sites workflow

compute_d4:
    time: 1-00:00:00
    nodes: 1
    mem: 16G
    cpus-per-task: 4

merge_d4:
    time: 1-00:00:00
    nodes: 1
    mem: 16G
    cpus-per-task: 2

callable_bed:
    time: 1-00:00:00
    nodes: 1
    mem: 64G
    cpus-per-task: 2

# bam2vcf workflows

bam2gvcf:
    time: 1-00:00:00
    nodes: 1
    mem: 32G
    cpus-per-task: 2

gvcf2DB:
    time: 1-00:00:00
    nodes: 1
    mem: 32G
    cpus-per-task: 2

DB2vcf:
    time: 1-00:00:00
    nodes: 1
    mem: 32G
    cpus-per-task: 2

bam2vcf:
    time: 1-00:00:00
    nodes: 1
    mem: 32G
    cpus-per-task: 2

filterVcfs:
    time: 1-00:00:00
    nodes: 1
    mem: 32G
    cpus-per-task: 2

gatherVcfs:
    time: 1-00:00:00
    nodes: 1
    mem: 64G
    cpus-per-task: 2

sortVcf:
    time: 1-00:00:00
    nodes: 1
    mem: 32G
    cpus-per-task: 2
